name: Docs
on:
  push:
    paths:
      - 'docs/*'

jobs:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Publish Docs
      uses: ./.github/actions/publish-docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
