name: Release
on:
  release:
    types: [published]

jobs:

  ## Publish docs
  release:
    name: Publish Docs
    runs-on: ubuntu-latest
    if: github.repository == 'markphelps/flipt'

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Publish Docs
      uses: ./.github/actions/publish-docs
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
